### ISSUE TITLE
issue2 モデル・ビュー・コントローラ作成

### ISSUE THREAD

**Issue by thori0908** [thori0908/railsgirls#2]
## 課題

railsではscaffoldコマンドを使用するだけで、モデル・ビュー・コントローラなどアプリケーションに必要なファイルを自動で作成することができます。以下が課題です。
- scaffoldコマンドについて説明してください。
- コマンドを用いて、ideaという名前のファイル群を作成してください。
- railsを再起動し、ブラウザでideaのページを確認してください。

Ref.
http://www.rubylife.jp/rails/scaffold/index1.html#section1

**Comment by thori0908** [comment]
```
 # MVCファイル作成
$ rbenv exec rails generate scaffold ideas

 # DB更新
$ ruby bin/rake db:migrate

 # rails起動
$ bundle exec rails server -b 0.0.0.0
```

**Comment by fr-sasaki** [comment]
ideaのページこれかな？
http://ec2-54-178-213-111.ap-northeast-1.compute.amazonaws.com:3000/ideas

**Comment by fr-sasaki** [comment]
@thori0908 
`scaffold`した際にファイルが生成されたと思うので、それをコミットしてPRを作成してください！
それと、今`create idea`しても空のデータが作られているので
http://railsgirls.jp/app/#idea--scaffold- 
のように`name`,`description`,`picture`が登録できるように修正をお願いします。

**Comment by thori0908** [comment]
```
 # idea削除 
$ bundle exec rails destroy scaffold idea

 # ideaを再び作成
$ bundle exec rails generate scaffold ideas name:string description:text picture:string

 # DB更新 
$ bundle exec rake db:migrate

 # rails起動
$ bundle exec rails server -b 0.0.0.0
```

**Comment by fr-matsuo** [comment]
確認しました、OKです。

**Comment by fr-sasaki** [comment]
OKなのでクローズします
